#!/usr/bin/env python

import sys

from packml_gui.packml_navigation import Packml_Navigation
from rqt_gui.main import Main

plugin = 'packml_gui.packml_navigation.Packml_Navigation'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Packml_Navigation.add_arguments))
